function cloneAgent(agent) {
  return {
    ...agent,
    inbox: [...agent.inbox],
    outbox: [...agent.outbox],
    history: [...agent.history],
  };
}

function cloneTask(task) {
  return { ...task };
}

function clamp(n, min, max) {
  return Math.max(min, Math.min(max, n));
}

function pickRandom(list) {
  return list[Math.floor(Math.random() * list.length)];
}

function findCompanionSkill(skill) {
  const map = {
    strategy: "research",
    workflow: "automation",
    research: "strategy",
    writing: "organize",
    code: "review",
    frontend: "ux",
    backend: "data",
    organize: "writing",
    voice: "support",
    sales: "marketing",
    review: "secure",
    publish: "launch",
    analyze: "strategy",
    secure: "review",
    marketing: "sales",
    translate: "localize",
    ux: "design",
    legal: "review",
    finance: "analyze",
    video: "audio",
    audio: "video",
    testing: "review",
    mobile: "ux",
    deployment: "workflow",
    automation: "workflow",
    schedule: "workflow",
    data: "analyze",
    seo: "marketing",
    support: "community",
    design: "ux",
    launch: "marketing",
    localize: "translate",
    docs: "organize",
  };
  return map[skill] || "workflow";
}

function buildReply(agent, message) {
  const templates = {
    strategy: "方針を整理して、次の一手を詰めます。",
    workflow: "受け渡し順を最適化します。",
    research: "情報を集めて、必要な根拠を確認します。",
    writing: "文章案を整えます。",
    code: "実装の形に落とし込みます。",
    frontend: "画面と操作感を整えます。",
    backend: "内部処理を安定させます。",
    organize: "情報を要約して並べます。",
    voice: "音声で扱いやすい形にします。",
    sales: "問い合わせ導線を磨きます。",
    review: "誤りがないか点検します。",
    publish: "公開しやすい形にします。",
    analyze: "数字を見て傾向を拾います。",
    secure: "安全面を確認します。",
    marketing: "反応が出る表現に寄せます。",
    translate: "多言語で自然にします。",
    ux: "使いやすさを上げます。",
    legal: "法務上のリスクを見ます。",
    finance: "予算と回収を見直します。",
    video: "映像の流れを作ります。",
    audio: "音の設計を詰めます。",
    testing: "テスト観点を増やします。",
    mobile: "スマホで崩れない形にします。",
    deployment: "公開手順を安定させます。",
    automation: "自動化フローを最適化します。",
    design: "見た目の整合性を上げます。",
    data: "データ構造を整理します。",
    growth: "伸びる導線を考えます。",
    support: "問い合わせ対応を整えます。",
    launch: "公開の最終確認をします。",
  };

  const line = templates[agent.primarySkill] || "進めます。";
  return `${agent.name}: ${line}｜受信: ${message.slice(0, 30)}`;
}

function buildStatusNote(agent, task) {
  return `進捗共有: ${task.name} を ${Math.round((task.progress || 0) * 100)}% まで進めています。`;
}

function randomRestMs() {
  return 2500 + Math.floor(Math.random() * 5500);
}

function createArtifact(task, agent) {
  const title = `${task.name} - ${agent.name}`;
  const stamp = new Date().toLocaleTimeString("ja-JP", { hour: "2-digit", minute: "2-digit" });

  switch (task.skill) {
    case "code":
    case "frontend":
    case "backend":
      return {
        kind: "code",
        title,
        body:
          `// generated by ${agent.name}\n` +
          `export function task_${task.id}() {\n` +
          `  return "${task.name} を実装した成果物";\n` +
          `}\n`,
        visualUri: null,
        stamp,
      };

    case "publish":
    case "deployment":
      return {
        kind: "page",
        title,
        body:
          `<section>\n` +
          `  <h1>${task.name}</h1>\n` +
          `  <p>${agent.name} が公開用の形に整えました。</p>\n` +
          `</section>`,
        visualUri: "https://picsum.photos/seed/publish-" + task.id + "/900/500",
        stamp,
      };

    case "video":
      return {
        kind: "video",
        title,
        body:
          `映像案:\n1. 導入\n2. 本題\n3. まとめ\n\n` +
          `${agent.name} が ${task.name} を動画構成に変換しました。`,
        visualUri: "https://picsum.photos/seed/video-" + task.id + "/900/500",
        stamp,
      };

    case "audio":
      return {
        kind: "audio",
        title,
        body:
          `音声案:\n- ナレーション\n- BGM\n- 効果音\n\n` +
          `${agent.name} が ${task.name} の音声設計を作成しました。`,
        visualUri: null,
        stamp,
      };

    case "design":
    case "ux":
    case "mobile":
      return {
        kind: "image",
        title,
        body:
          `UI案:\n- レイアウト整理\n- 視線誘導\n- 余白最適化\n\n` +
          `${agent.name} が ${task.name} をデザインしました。`,
        visualUri: "https://picsum.photos/seed/design-" + task.id + "/900/500",
        stamp,
      };

    case "research":
    case "analyze":
      return {
        kind: "report",
        title,
        body:
          `要点:\n- 主要な傾向を抽出\n- 競合や市場を比較\n- 次の打ち手を提案\n\n` +
          `${agent.name} が ${task.name} を分析しました。`,
        visualUri: null,
        stamp,
      };

    case "translate":
    case "localize":
      return {
        kind: "text",
        title,
        body:
          `原文に自然な多言語表現を付与しました。\n` +
          `${agent.name} が ${task.name} を翻訳しました。`,
        visualUri: null,
        stamp,
      };

    default:
      return {
        kind: "text",
        title,
        body:
          `${agent.name} が ${task.name} を完了しました。\n` +
          `実行時刻: ${stamp}`,
        visualUri: null,
        stamp,
      };
  }
}

function chooseRecipient(agents, sender, task) {
  const targetSkill = findCompanionSkill(task.skill);
  const candidates = agents.filter(
    (a) =>
      a.id !== sender.id &&
      a.status !== "rest" &&
      (a.skills.includes(targetSkill) || a.skills.includes("workflow") || a.skills.includes("review"))
  );

  if (candidates.length) return pickRandom(candidates);
  const fallback = agents.filter((a) => a.id !== sender.id);
  return fallback.length ? pickRandom(fallback) : null;
}

function pushLog(logs, kind, text) {
  logs.push({
    id: `${kind}-${Date.now()}-${Math.floor(Math.random() * 100000)}`,
    ts: Date.now(),
    kind,
    text,
  });
}

function trimArray(arr, max) {
  if (arr.length > max) return arr.slice(arr.length - max);
  return arr;
}

export function stepEngine(state) {
  const now = Date.now();
  const agents = state.agents.map(cloneAgent);
  const tasks = state.tasks.map(cloneTask);
  const logs = [...state.logs];

  const taskMap = new Map(tasks.map((t) => [t.id, t]));

  for (const agent of agents) {
    if (agent.restUntil && agent.restUntil <= now) {
      agent.restUntil = 0;
      if (agent.status === "rest") {
        agent.status = "idle";
        pushLog(logs, "system", `${agent.name} は休憩を終えました。`);
      }
    } else if (agent.restUntil && agent.restUntil > now) {
      agent.status = "rest";
    }

    while (agent.inbox.length) {
      const msg = agent.inbox.shift();
      const reply = buildReply(agent, msg);
      agent.outbox.push(reply);
      agent.history.push({ ts: now, type: "in", text: msg });
      agent.history.push({ ts: now, type: "out", text: reply });
      pushLog(logs, "chat", `${agent.name} 受信: ${msg}`);
      pushLog(logs, "chat", `${agent.name} 返信: ${reply}`);
    }

    agent.history = trimArray(agent.history, 25);
    agent.outbox = trimArray(agent.outbox, 20);
  }

  for (const agent of agents) {
    if (!agent.currentTaskId) continue;

    const task = taskMap.get(agent.currentTaskId);
    if (!task || task.status === "done") {
      agent.currentTaskId = null;
      agent.currentProgress = 0;
      agent.status = "idle";
      continue;
    }

    const speed =
      0.12 +
      (agent.skills.includes(task.skill) ? 0.18 : 0) +
      (task.skill === agent.primarySkill ? 0.16 : 0) +
      Math.random() * 0.10;

    task.progress = clamp((task.progress || 0) + speed, 0, 1);
    task.updatedAt = now;
    agent.currentProgress = task.progress;

    if (Math.random() < 0.18) {
      const recipient = chooseRecipient(agents, agent, task);
      if (recipient) {
        const note = buildStatusNote(agent, task);
        recipient.inbox.push(note);
        pushLog(logs, "chat", `${agent.name} → ${recipient.name}: ${note}`);
      }
    }

    if (task.progress >= 1) {
      task.progress = 1;
      task.status = "done";
      task.completedAt = now;
      task.completedBy = agent.id;
      task.completedByName = agent.name;
      task.output = createArtifact(task, agent);
      agent.currentTaskId = null;
      agent.currentProgress = 1;
      agent.status = "idle";
      agent.artifact = task.output;
      agent.history.push({ ts: now, type: "done", text: `${task.name} を完了` });
      pushLog(logs, "task", `完了: ${agent.name} が「${task.name}」を仕上げました。`);
    } else {
      task.status = "running";
      agent.status = "busy";
    }
  }

  const pending = tasks
    .filter((t) => t.status !== "done" && !t.assignedTo)
    .sort((a, b) => (b.priority || 0) - (a.priority || 0) || a.id - b.id);

  for (const agent of agents) {
    if (agent.status !== "idle" || agent.currentTaskId) continue;

    const task = pending.find((t) => agent.skills.includes(t.skill) && !t.assignedTo);
    if (task) {
      task.assignedTo = agent.id;
      task.assignedToName = agent.name;
      task.startedAt = now;
      task.status = "running";
      agent.currentTaskId = task.id;
      agent.currentProgress = task.progress || 0;
      agent.status = "busy";
      pushLog(logs, "task", `開始: ${agent.name} が「${task.name}」を担当しました。`);

      const recipient = chooseRecipient(agents, agent, task);
      if (recipient && Math.random() < 0.45) {
        const note = `着手しました: ${task.name}`;
        recipient.inbox.push(note);
        pushLog(logs, "chat", `${agent.name} → ${recipient.name}: ${note}`);
      }
    } else if (Math.random() < 0.05) {
      agent.status = "rest";
      agent.restUntil = now + randomRestMs();
      pushLog(logs, "system", `${agent.name} は自律的に休憩に入りました。`);
    }
  }

  if (Math.random() < 0.35) {
    const speaker = pickRandom(agents.filter((a) => a.status !== "rest"));
    const listener = speaker ? chooseRecipient(agents, speaker, { skill: "workflow" }) : null;
    if (speaker && listener) {
      const smallTalk = `進捗確認: ${speaker.currentTaskId ? "作業中" : "次の仕事を待機中"}。`;
      listener.inbox.push(smallTalk);
      pushLog(logs, "chat", `${speaker.name} → ${listener.name}: ${smallTalk}`);
    }
  }

  for (const agent of agents) {
    if (!agent.currentTaskId && !agent.restUntil) {
      agent.status = "idle";
    }
  }

  return {
    ...state,
    agents,
    tasks,
    logs: trimArray(logs, 160),
  };
             }
